### ISSUE TITLE
PHP build-in server does not stop after batch termination on Windows 10

### ISSUE THREAD

**Issue by aliakseimaniuk** [deathbaba/landing-php#38]

**Comment by biodranik** [comment]
Процесс висит в памяти после закрытия окон cmd?

**Comment by aliakseimaniuk** [comment]
Если закрыть cmd-окно, то процессы убиваются. Но если я останавливаю скрипт в рамках одного cmd-окна, php-сервер не останавливается. Если я второй раз вызову watch.cmd у меня запустится еще один php сервер. 

Я подумал, что можно как-то перезапускать или останавливать php-сервер, когда ты останавливаешь скрипт. Пока это не критично, потому что можно закрывать окно.

**Comment by biodranik** [comment]
Почитал доки, правильный способ здесь будет прерывать скрипт не по Ctrl+C, а по Ctrl+Break. По-другому красиво через cmd, к сожалению, никак не сделаешь.
